/*
 Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/* @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually
  // tutorialSidebar: [
  //   'intro',
  //   'hello',
  //   {
  //     type: 'category',
  //     label: 'Tutorial',
  //     items: ['tutorial-basics/create-a-document'],
  //   },
  // ],
};

module.exports = {
  deep_learning: [
    // {
    //   type: 'doc',
    //   id: 'Deep-Learning/intro',
    //   label: '欢迎',
    // },
    // {
    //   type: 'doc',
    //   id: 'Deep-Learning/Fill-The-Gaps',
    //   label: '查漏补缺',
    // },
    // {
    //   type: 'category',
    //   label: '基础知识',
    //   items: [
    //     {
    //     type: 'autogenerated',
    //     dirName: 'Deep-Learning/3-基础知识',
    //     }
    //   ]
    // },
    {
      type: 'autogenerated',
      dirName: 'Deep-Learning',
    }
  ],
  gpu_server: [
    {
      type: 'autogenerated',
      dirName: 'GPU-Server',
    }
  ],
  tui_mian: [
    {
      type: 'autogenerated',
      dirName: 'Tui-Mian',
    }
  ],
  algorithms: [
    {
      type: 'autogenerated',
      dirName: 'Algorithms',
    }
  ],
  curriculum: [
    {
      type: 'autogenerated',
      dirName: 'Curriculum',
    }
  ],
  others: [
    {
      type: 'autogenerated',
      dirName: 'Others',
    }
  ],
  acknowledgement: [
    {
      type: 'autogenerated',
      dirName: 'Acknowledgement',
    }
  ],

  // 在这里进行Sidebar的客制化，做到实际目录中为英文（URL也是英文），但Sidebar仍然显示为中文，及手动设置Sidebar
  // deep_learning: [
  //   {
  //     type: 'doc',
  //     id: 'Deep-Learning/intro',
  //     label: '欢迎',
  //   },
  //   {
  //     type: 'doc',
  //     id: 'Deep-Learning/Fill-The-Gaps',
  //     label: '查漏补缺',
  //   },
  //   {
  //     type: 'category',
  //     label: '基础知识',
  //     items: [
  //       {
  //       type: 'autogenerated',
  //       dirName: 'Deep-Learning/3-基础知识',
  //       }
  //     ]
  //   },
  // ],
};
